services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    image: "node:18-alpine"
    working_dir: /myapp/frontend
    volumes:
      - ./frontend:/myapp/frontend
    command: "npm start"
    ports:
      - "80:3000"
    depends_on:
      - backend
